class StringsEn {
  Map<String, String> getStrings() {
    return {
      'appTitle': 'Welcome to Cab-Sud',
      'descriptionText': 'Cab-Sud, specialist in transportation in Marseille, offers a fast and pleasant service.',

      'airport_transfer_title': 'AIRPORT TRANSFER',
      'airport_transfer_description': 'Cab-Sud, your solution for airport transfers in Marseille, combines convenience and style.',
      'cruiseTransferTitle': 'CRUISE PORT TRANSFER',
      'cruiseTransferDescription': 'Cab-Sud, your tailored cruise port transfer with punctuality and quality.',
      'trainTransferTitle': 'TRAIN STATION TRANSFER',
      'trainTransferDescription': 'Cab-Sud, your Marseille partner for comfortable and efficient journeys.',
      'introTitle5': 'WELCOME TO CAB-SUD',
      'introDescription5': 'Cab-Sud, premium transport in Marseille to explore the region with peace of mind.',
      'introTitle6': 'PRIVATE DRIVER SERVICE',
      'introDescription6': 'For your events, our vehicles offer safety and distinction.',

      'skipButton': 'SKIP',
      'nextButton': 'NEXT',
      'getStartedButton': 'GET STARTED',

      'appTitle2': 'Welcome to Cab-Sud',
      'loginTitle': 'Login',
      'emailHint': 'Email',
      'passwordHint': 'Password',
      'loginButton': 'Login',
      'signUpText': "Don't have an account?",
      'signUpButton': 'Sign Up',
      'emailRequired': 'Email is required',
      'passwordRequired': 'Password is required',
      'loginFailed': 'Login Failed',

      'loginFailed': 'Login Failed',
      'emailRequired': 'Email is required',
      'passwordRequired': 'Password is required',

      'email': 'Email',
      'password': 'Password',
      'confirmPassword': 'Confirm Password',
      'signUp': 'Sign Up',
      'googleSignUp': 'Sign up with Google',
      'alreadyHaveAccount': 'Already have an account?',
      'login': 'Login',
      'passwordRequired2': 'Password is required',
      'emailRequired2': 'Email is required',
      'confirmPasswordRequired': 'Confirm Password is required',
      'passwordMismatch': 'Passwords do not match',
      'passwordStrength': 'Must contain 1 uppercase, 1 number, 1 special character',
      'termsOfService': 'Terms of Service',
      'agree': 'I Agree',
      'cancel': 'Cancel',
      'signUpSuccess': 'Sign-up successful! Please verify your email.',
      'signUpFailed': 'Sign-Up Failed: ',
      'googleSignInFailed': 'Google Sign-In Failed',
      'emailInvalid': 'Enter a valid email',
      'termsOfServiceContent': '''
Welcome to our CAB-SUD. By signing up and using our services, you agree to the following Terms of Service:

1. You agree to use the app for lawful ride-sharing purposes only.
2. You are responsible for keeping your account secure.
3. Payments for rides must be made through the app.
4. We do not sell or misuse your data. Your location and personal info are only used to operate the app.
5. We encrypt and securely store your data.
6. Cancellation and refund policies apply as listed in the app.
7. We may update these terms, and continued use means you accept changes.

For support, contact us at khaleddarradji@gmail.com.
      ''',
      'servicesTitle': 'Our Services',
      'chauffeurTitle': 'Driver',
      'chauffeurDesc': 'Professional, punctual and discreet drivers.',
      'prixFixesTitle': 'Fixed prices',
      'prixFixesDesc': 'All our prices are fixed and known in advance.',
      'vehiculesTitle': 'Vehicles',
      'vehiculesDesc': 'Recent, spacious and comfortable cars.',
      'wifiTitle': 'Wifi',
      'wifiDesc': 'All our vehicles offer onboard wifi.',
      'enfantsTitle': 'Children',
      'enfantsDesc': 'Baby seat or booster seat free: on request.',
      'paiementTitle': 'Payment',
      'paiementDesc': 'Online or onboard payment.',
      'paiementSecuTitle': 'Secure Online Payment',
      'paiementSecuDesc': 'Credit card, American Express.',
      'gotoHomeBtn': 'Go to Home Page',

      'contactTitle': 'Contact Us',
      'contactSubtitle': 'We would love to hear from you! Please fill in the form below.',
      'fullNameLabel': 'Full Name',
      'fullNameHint': 'Enter your full name',
      'phoneLabel': 'Phone Number',
      'phoneHint': 'Enter your phone number',
      'emailLabel': 'Email',
      'emailHint2': 'Enter your email address',
      'submitButton': 'Submit',
      'successMessage': 'Submitting your contact details',
      'nameValidation': 'Please enter your name',
      'phoneValidation': 'Please enter your phone number',
      'emailValidation': 'Please enter your email',
      'emailFormatValidation': 'Please enter a valid email',

      'vehicleSelectionTitle': 'Choose your ideal ride',
      'vehicleTypeEco': 'Eco',
      'vehicleTypeBerline': 'Berline',
      'vehicleTypeVan': 'Van',
      'vehicleDescEco': 'Economic & Comfortable',
      'vehicleDescBerline': 'Premium Comfort',
      'vehicleDescVan': 'Group Travel',
      'vehiclePassengers': 'Passengers',
      'vehicleBags': 'Bags',
      'vehiclePrice': 'Price',
      'vehicleFixedPrice': 'Fixed Price',
      'continueButton': 'CONTINUE',

      'appointmentTitle': "Book an appointment",
      'appointmentSubtitle': "Choose a date and time that suits you",
      'selectDate': "Select a date",
      'selectTime': "Select a time",
      'confirmAppointment': "Confirm appointment",
      'appointmentSuccess': "Your appointment has been booked!",
      'appointmentError': "Failed to book appointment. Please try again.",
      'dateRequired': "Please select a date",
      'timeRequired': "Please select a time",

      'faireUneCommande': 'Place an Order',
      'miseADisposition': 'Availability Service',
      'nosServices': 'Our Services',
      'home': 'Home',
      'contact': 'Contact',
      'settings': 'Settings',
      'adresseDePickup': 'Pickup Address',
      'adresseDeDestination': 'Destination Address',
      'distance': 'Distance',
      'duree': 'Duration',
      'saisissezVotreAdresse': 'Enter Your Address',
      'calculerLaDistance': 'Calculate Distance',

      'accueil': 'Home',
      'contact1': 'Contact',
      'parametres': 'Settings',
      'faireUneCommande2': 'Place an Order',
      'miseADisposition2': 'Chauffeur Service',
      'nosServices1': 'Our Services',

      'nosServices2': 'Our Services',
      'selectService': 'Select a Service',
      'airportTransport': 'Airport Transport',
      'cruiseTransport': 'Cruise Transport',
      'trainStationTransport': 'Train Station Transport',
      'carAtDisposal': 'Car at Disposal',
      'tourism': 'Tourism',
      'selected': 'Selected',
      'continueButton2': 'CONTINUE',

      'infoTitle': 'Important Information',
      'infoDescription': 'The reservation service requires payment to be made exclusively inside the vehicle.',
      'understood': 'I UNDERSTAND',
      'planJourney': 'Plan Your Journey',
      'departureAddress': 'Departure Address',
      'durationLabel': 'Duration (Hours)',
      'hour': 'Hour',
      'hours': 'Hours',
      'continue': 'CONTINUE',

      'commandSuccessMessage': 'Command completed successfully!\nYou will be contacted soon.',
      'backToHome': 'Go back to the home page',
    };
  }
}

